apiVersion: v1
kind: ConfigMap
metadata:
  name: jimsk
  labels:
    app: jimsk
data:
  APP_PORT: :80
  APP_STATIC: /etc/jimsk/static
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jimsk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jimsk
  template:
    metadata:
      labels:
        app: jimsk
    spec:
      restartPolicy: Always
      containers:
      - name: jimsk
        image: jimlearnstofly/jimsk:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: jimsk
            optional: false
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jimsk
  labels:
    app: jimsk
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: jimsk
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jimsk
  labels:
    app: jimsk
spec:
  hosts:
  - "jimsk.com"
  - "www.jimsk.com"
  gateways:
  - bazare
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: jimsk

